version: '3'
services:
  db:
    build: ./lib/database/docker
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 5s
      retries: 10
  account:
    build:
      context: ./
      dockerfile: ./cmd/account/Dockerfile
    environment:
      DB_HOST: "db"
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  balance:
    build:
      context: ./
      dockerfile: ./cmd/balance/Dockerfile
    environment:
      DB_HOST: "db"
    restart: always
    depends_on:
      - "db"
    ports:
      - 8081:8081
  transaction:
    build:
      context: ./
      dockerfile: ./cmd/transaction/Dockerfile
    environment:
      DB_HOST: "db"
      BALANCE_HOST: "balance"
    restart: always
    depends_on:
      - "db"
    ports:
      - 8082:8082